### PR TITLE
New design!

### PR DESCRIPTION
**Pull request by brendastorer**
This also includes:
- addition of Sass, Bourbon and Bitters
- Logo as inline SVG for using consistent color throughout the site and better resolution

screen shot 2016-01-13 at 3 47 17 pm

### CODE REVIEW

**Comment by tabfugnic** [comment]
crazy-dance
30-rock
mind_blown
request-five

**Comment by tabfugnic** [comment]
I will do actual code review a bit later

**Comment by tabfugnic** [comment]
Looks amazing! took a look at the code, looks good to me. I may try to tackle the bourbon thing, which appears to have some path to use the gem, though it's pretty convoluted. Sounds like a PR!!!

**Comment by tabfugnic** [comment]
The bourbon stuff is crazy yo. I feel like you can merge this whenever

**Comment by brendastorer** [comment]
Thanks! I got to work on some responsive stuff, and then I'll merge her on in.

**Comment by tabfugnic** [comment]
perf, thank you so much!

**Comment by hrs** [comment]
Well shit, @brendastorer, this is awesome! Nicely done!

@tabfugnic Did you verify that everything works OK in `eww`? I feel like we should probably make sure that the site still works from within Emacs. :grinning:

**Comment by tabfugnic** [comment]
@hrs very good point

**Comment by tabfugnic** [comment]
Works very well in EWW, only issue is that svg doesn't show up. @brendastorer is there anyway to get alt text on svg?

2016-01-15-133503_950x994_scrot

**Comment by tabfugnic** [comment]
also a huge sad that marquee tags are not supported in `eww` :(

**Comment by tabfugnic** [comment]
@brendastorer Anything preventing me from merging this?

**Comment by brendastorer** [comment]
@tabfugnic Yes, and sorry for the delay. It's not responsive yet and I want to add an image fallback for the SVG. If you want I can merge it as is and then I'll work on those things separately, lmk.

**Comment by tabfugnic** [comment]
Work away. I'm still going to announce it tonight either way

**Comment by tabfugnic** [comment]
at the meetup, I will more formally announce it when it is done

**Comment by tabfugnic** [comment]
@brendastorer 

2016-02-01-171032_1016x1008_scrot

**Comment by tabfugnic** [comment]
There it is! It shows the svg box too, but there's no way around that i don't think

**Comment by brendastorer** [comment]
Fallback counts on JS. I have an idea though. I'll work on it in another branch.

**Pull request merged**
